# Generated by Django 5.0.4 on 2024-04-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_categorydata_customers_inventory_itemdata_orders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='photodata',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('photo', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='itemdata',
            old_name='warranty',
            new_name='image_url',
        ),
    ]
