# Generated by Django 5.0.4 on 2024-04-29 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_photodata_rename_warranty_itemdata_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='itemdata',
            name='image_url',
        ),
    ]
