# Generated by Django 5.0.4 on 2024-04-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_delete_inventory_remove_itemdata_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='discount',
            field=models.IntegerField(null=True),
        ),
    ]
