# Generated by Django 5.0.4 on 2024-05-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_cart_orders_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdata',
            name='email_of_seller',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itemdata',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
