# Generated by Django 5.0.4 on 2024-05-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_cart_customer_id_cart_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
