# Generated by Django 5.0.4 on 2024-05-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_orders_customer_id_orders_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='discount',
            new_name='cart_id',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='total_amt',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_date',
        ),
        migrations.AddField(
            model_name='orders',
            name='product_id',
            field=models.IntegerField(null=True),
        ),
    ]
